name: Deploy Google Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy ContactForm \
            --runtime go123 \
            --trigger-http \
            --allow-unauthenticated \
            --set-env-vars "SMTP_USER=${{ secrets.SMTP_USER }},SMTP_PASS=${{ secrets.SMTP_PASS }},SMTP_TO=${{ secrets.SMTP_TO }},SMTP_PROVIDERS=${{ secrets.SMTP_PROVIDERS }}"

      - name: Grant Cloud Functions roles (manual step)
        run: |
          echo "Ensure your service account has the following roles:"
          echo "- roles/cloudfunctions.developer"
          echo "- roles/cloudfunctions.viewer"
          echo "- roles/iam.serviceAccountUser (if needed)"
          echo "You can grant these roles in the Google Cloud Console IAM page: https://console.cloud.google.com/iam-admin/iam"
